INSERT INTO APFS.SYS_ROLE (ROLE_ID, UP_ROLE_ID, ROLE_NM, RGTR_NO, REG_YMD) VALUES ('ROLE_AUTH_SYS',       'NONE', '시스템관리자', 'system', NOW());
INSERT INTO APFS.SYS_ROLE (ROLE_ID, UP_ROLE_ID, ROLE_NM, RGTR_NO, REG_YMD) VALUES ('ROLE_AUTH_ADM',       'NONE', '운영관리자', 'system', NOW());
INSERT INTO APFS.SYS_ROLE (ROLE_ID, UP_ROLE_ID, ROLE_NM, RGTR_NO, REG_YMD) VALUES ('ROLE_AUTH_USR',       'NONE', '일반회원사용자', 'system', NOW());
INSERT INTO APFS.SYS_ROLE (ROLE_ID, UP_ROLE_ID, ROLE_NM, RGTR_NO, REG_YMD) VALUES ('ROLE_AUTH_COP',       'NONE', '기업회원사용자', 'system', NOW());
INSERT INTO APFS.SYS_ROLE (ROLE_ID, UP_ROLE_ID, ROLE_NM, RGTR_NO, REG_YMD) VALUES ('ROLE_USR_RESTRICTED', 'NONE', '비회원사용자', 'system', NOW());
