CREATE SEQUENCE APFS.SEQ_USER START 1;
CREATE SEQUENCE APFS.SEQ_MAIL_HST START 1;
CREATE SEQUENCE APFS.SEQ_APLY_FILE START 1;
CREATE SEQUENCE APFS.SEQ_FILE START 1;

CREATE TABLE APFS.TMP_USER (
	USER_NO VARCHAR(20) NOT NULL,
	USER_ID VARCHAR(100),
	USER_NM VARCHAR(40),
	USER_CD VARCHAR(10),
	PSWD  VARCHAR(100),
	EMAIL VARCHAR(100),
	MOBILE VARCHAR(20),
	JOIN_YMD VARCHAR(8),
	WHDWL_YMD VARCHAR(8),
	PSWD_LOCK_YMD VARCHAR(8),
	PSWD_ERR_CNT SMALLINT,
	PSWD_CHG_YMD VARCHAR(8),
	PSWD_NEXT_YMD VARCHAR(8),
	LST_LGN_DT DATE,
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (USER_NO)
);
COMMENT ON TABLE  APFS.TMP_USER IS '사용자정보';
COMMENT ON COLUMN APFS.TMP_USER.USER_NO IS '사용자번호';
COMMENT ON COLUMN APFS.TMP_USER.USER_ID IS '사용자ID';
COMMENT ON COLUMN APFS.TMP_USER.USER_NM IS '사용자명';
COMMENT ON COLUMN APFS.TMP_USER.USER_CD IS '사용자가입유형';
COMMENT ON COLUMN APFS.TMP_USER.PSWD IS '비밀번호';
COMMENT ON COLUMN APFS.TMP_USER.EMAIL IS '이메일';
COMMENT ON COLUMN APFS.TMP_USER.MOBILE IS '휴대전화번호';
COMMENT ON COLUMN APFS.TMP_USER.JOIN_YMD IS '가입일자';
COMMENT ON COLUMN APFS.TMP_USER.WHDWL_YMD IS '탈퇴일자';
COMMENT ON COLUMN APFS.TMP_USER.PSWD_LOCK_YMD IS '비밀번호잠금일자';
COMMENT ON COLUMN APFS.TMP_USER.PSWD_ERR_CNT IS '비밀번호오류수';
COMMENT ON COLUMN APFS.TMP_USER.PSWD_CHG_YMD IS '비밀번호변경일자';
COMMENT ON COLUMN APFS.TMP_USER.PSWD_NEXT_YMD IS '비밀번호다음일자';
COMMENT ON COLUMN APFS.TMP_USER.LST_LGN_DT IS '마지막로그인일시';
COMMENT ON COLUMN APFS.TMP_USER.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.TMP_USER.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.TMP_USER.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.TMP_USER.MDFCN_YMD IS '수정일자';

CREATE TABLE APFS.TMP_OAUTH (
	USER_NO VARCHAR(20) NOT NULL,
	OATH_CD VARCHAR(20) NOT NULL,
	OATH_ID VARCHAR(50),
	USER_NM VARCHAR(40),
	EMAIL VARCHAR(100),
	MOBILE VARCHAR(20),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (USER_NO, OATH_CD)
);
COMMENT ON TABLE  APFS.TMP_OAUTH IS '사용자정보';
COMMENT ON COLUMN APFS.TMP_OAUTH.USER_NO IS '사용자번호';
COMMENT ON COLUMN APFS.TMP_OAUTH.OATH_CD IS 'OAUTH 서비스코드';
COMMENT ON COLUMN APFS.TMP_OAUTH.USER_NM IS '사용자명';
COMMENT ON COLUMN APFS.TMP_OAUTH.OATH_ID IS 'OAUTH 식별ID';
COMMENT ON COLUMN APFS.TMP_OAUTH.EMAIL IS '이메일';
COMMENT ON COLUMN APFS.TMP_OAUTH.MOBILE IS '휴대전화번호';
COMMENT ON COLUMN APFS.TMP_OAUTH.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.TMP_OAUTH.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.TMP_OAUTH.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.TMP_OAUTH.MDFCN_YMD IS '수정일자';

CREATE TABLE APFS.TMP_MAIL_HST (
	SN INTEGER NOT NULL,
	USER_NO VARCHAR(20),
	TO_ADDR VARCHAR(50),
	TO_NAME VARCHAR(40),
	FR_ADDR VARCHAR(50),
	FR_NAME VARCHAR(40),
	SUBJECT VARCHAR(200),
	CONTENT TEXT,
	TEMPLATE VARCHAR(30),
	SEND_DT DATE,
	SEND_CD VARCHAR(20),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (SN)
);
COMMENT ON TABLE  APFS.TMP_MAIL_HST IS 'TMP_MAIL_HST';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.SN IS '일련번호';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.USER_NO IS '사용자번호';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.SEND_DT IS '발송일시';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.SEND_CD IS '발송결과코드';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.SUBJECT IS '메일제목';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.CONTENT IS '메일내용';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.TEMPLATE IS '템플릿파일';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.TO_ADDR IS '수신이메일주소';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.TO_NAME IS '수신자명';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.FR_ADDR IS '발신이메일주소';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.FR_NAME IS '발신자명';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.TMP_MAIL_HST.MDFCN_YMD IS '수정일자';


CREATE TABLE APFS.TMP_FILE (
	SN NUMERIC(10,0) NOT NULL,
	DTY_SE_CD VARCHAR(10),
	DCMT_NO VARCHAR(10),
	FILE_PATH VARCHAR(200),
	STRG_FILE_NM VARCHAR(100),
	FILE_NM VARCHAR(200),
	FILE_SZ NUMERIC(14,0),
	DEL_YN CHAR(1),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (SN)
);
COMMENT ON TABLE APFS.TMP_FILE IS '공통첨부파일';
COMMENT ON COLUMN APFS.TMP_FILE.SN IS '일련번호';
COMMENT ON COLUMN APFS.TMP_FILE.DTY_SE_CD IS '구분코드';
COMMENT ON COLUMN APFS.TMP_FILE.DCMT_NO IS '문서번호';
COMMENT ON COLUMN APFS.TMP_FILE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN APFS.TMP_FILE.STRG_FILE_NM IS '저장파일명';
COMMENT ON COLUMN APFS.TMP_FILE.FILE_NM IS '파일명';
COMMENT ON COLUMN APFS.TMP_FILE.FILE_SZ IS '파일크기';
COMMENT ON COLUMN APFS.TMP_FILE.DEL_YN IS '삭제여부';
COMMENT ON COLUMN APFS.TMP_FILE.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.TMP_FILE.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.TMP_FILE.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.TMP_FILE.MDFCN_YMD IS '수정일자';

CREATE TABLE APFS.TMP_APLY_FILE (
	SN NUMERIC(10,0) NOT NULL,
	DTY_SE_CD VARCHAR(10),
	DCMT_NO VARCHAR(10),
	DTL_DCMT_NO NUMERIC(10,0),
	PAPE_CD VARCHAR(10),
	FILE_PATH VARCHAR(200),
	STRG_FILE_NM VARCHAR(100),
	FILE_NM VARCHAR(200),
	FILE_SZ NUMERIC(14,0),
	PRCS_STUS_CD VARCHAR(2),
	PRCS_CN VARCHAR(2000),
	DEL_YN CHAR(1),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	MNGR_REG_YN CHAR(1),
	PRIMARY KEY (SN)
);
COMMENT ON TABLE APFS.TMP_APLY_FILE IS '신청첨부파일';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.SN IS '일련번호';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.DTY_SE_CD IS '업무구분코드';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.DCMT_NO IS '문서번호';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.DTL_DCMT_NO IS '세부문서번호';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.PAPE_CD IS '서류코드';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.STRG_FILE_NM IS '저장파일명';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.FILE_NM IS '파일명';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.FILE_SZ IS '파일크기';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.PRCS_STUS_CD IS '처리상태코드';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.PRCS_CN IS '처리내용';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.DEL_YN IS '삭제여부';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.MDFCN_YMD IS '수정일자';
COMMENT ON COLUMN APFS.TMP_APLY_FILE.MNGR_REG_YN IS '관리자등록여부';

CREATE TABLE APFS.TMP_PAPE_CODE (
	PAPE_CD VARCHAR(10) NOT NULL,
	UP_PAPE_CD VARCHAR(10) NOT NULL,
	PAPE_NM VARCHAR(100),
	PAPE_DTY_SE_CD VARCHAR(10),
	LIMT_CNT NUMERIC(2,0),
	ESNTL_YN CHAR(1),
	CD_ORDR NUMERIC(5,0),
	FILE_NM VARCHAR(200),
	FILE_PATH VARCHAR(200),
	DOWN_CNT NUMERIC(10),
	DOWN_TRGT_YN CHAR(1),
	USE_YN CHAR(1),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (PAPE_CD, UP_PAPE_CD)
);
COMMENT ON TABLE APFS.TMP_PAPE_CODE IS '서류코드관리';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.PAPE_CD IS '서류코드';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.UP_PAPE_CD IS '상위서류코드';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.PAPE_NM IS '서류명';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.PAPE_DTY_SE_CD IS '업무구분코드';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.LIMT_CNT IS '제한수';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.ESNTL_YN IS '필수여부';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.CD_ORDR IS '코드순서';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.FILE_NM IS '파일명';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.DOWN_CNT IS '다운로드수';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.DOWN_TRGT_YN IS '다운로드대상여부';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.USE_YN IS '사용여부';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.TMP_PAPE_CODE.MDFCN_YMD IS '수정일자';


