CREATE SEQUENCE APFS.SEQ_CNTN_HST START 1;
CREATE SEQUENCE APFS.SEQ_LGN_HST START 1;
CREATE SEQUENCE APFS.SEQ_INFO_HST START 1;
CREATE SEQUENCE APFS.SEQ_DOWN_HST START 1;

CREATE TABLE APFS.SYS_CODE (
	CD_ID VARCHAR(20) NOT NULL,
	UP_CD_ID VARCHAR(20) NOT NULL,
	CD_NM VARCHAR(200),
	CD_CN VARCHAR(2000),
	VLD_BGNG_YMD VARCHAR(8),
	VLD_END_YMD VARCHAR(8),
	CD_ORDR SMALLINT,
	USE_YN CHAR(1),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (CD_ID,UP_CD_ID)
);
COMMENT ON  TABLE APFS.SYS_CODE IS '코드관리';
COMMENT ON COLUMN APFS.SYS_CODE.CD_ID IS '코드ID';
COMMENT ON COLUMN APFS.SYS_CODE.UP_CD_ID IS '상위코드ID';
COMMENT ON COLUMN APFS.SYS_CODE.CD_NM IS '코드명';
COMMENT ON COLUMN APFS.SYS_CODE.CD_CN IS '코드내용';
COMMENT ON COLUMN APFS.SYS_CODE.VLD_BGNG_YMD IS '유효시작일자';
COMMENT ON COLUMN APFS.SYS_CODE.VLD_END_YMD IS '유효종료일자';
COMMENT ON COLUMN APFS.SYS_CODE.CD_ORDR IS '코드순서';
COMMENT ON COLUMN APFS.SYS_CODE.USE_YN IS '사용여부';
COMMENT ON COLUMN APFS.SYS_CODE.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.SYS_CODE.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.SYS_CODE.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.SYS_CODE.MDFCN_YMD IS '수정일자';

CREATE TABLE APFS.SYS_MENU (
	MENU_ID VARCHAR(20) NOT NULL,
	UP_MENU_ID VARCHAR(20),
	MENU_NM VARCHAR(100),
	MENU_LVL  SMALLINT,
	MENU_ORDR SMALLINT,
	TRGT_URL VARCHAR(500),
	POPUP_YN CHAR(1),
	SYS_SE_CD VARCHAR(3),
	USE_YN CHAR(1),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (MENU_ID)
);
COMMENT ON TABLE  APFS.SYS_MENU IS '메뉴관리';
COMMENT ON COLUMN APFS.SYS_MENU.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN APFS.SYS_MENU.UP_MENU_ID IS '상위메뉴ID';
COMMENT ON COLUMN APFS.SYS_MENU.MENU_NM IS '메뉴명';
COMMENT ON COLUMN APFS.SYS_MENU.MENU_LVL IS '메뉴레벨';
COMMENT ON COLUMN APFS.SYS_MENU.MENU_ORDR IS '메뉴순서';
COMMENT ON COLUMN APFS.SYS_MENU.TRGT_URL IS '대상URL';
COMMENT ON COLUMN APFS.SYS_MENU.POPUP_YN IS '팝업여부';
COMMENT ON COLUMN APFS.SYS_MENU.SYS_SE_CD IS '시스템구분코드';
COMMENT ON COLUMN APFS.SYS_MENU.USE_YN IS '사용여부';
COMMENT ON COLUMN APFS.SYS_MENU.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.SYS_MENU.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.SYS_MENU.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.SYS_MENU.MDFCN_YMD IS '수정일자';

CREATE TABLE APFS.SYS_PROG (
	PROG_ID VARCHAR(20) NOT NULL,
	PROG_NM VARCHAR(200),
	PROG_URL VARCHAR(500),
	PROG_TY VARCHAR(5),
	MENU_ID VARCHAR(20),
	PROG_ORDR SMALLINT,
	SYS_SE_CD VARCHAR(3),
	USE_YN CHAR(1),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (PROG_ID)
);
COMMENT ON TABLE  APFS.SYS_PROG IS '프로그램관리';
COMMENT ON COLUMN APFS.SYS_PROG.PROG_ID IS '프로그램ID';
COMMENT ON COLUMN APFS.SYS_PROG.PROG_NM IS '프로그램명';
COMMENT ON COLUMN APFS.SYS_PROG.PROG_URL IS '프로그램URL';
COMMENT ON COLUMN APFS.SYS_PROG.PROG_TY IS '프로그램유형';
COMMENT ON COLUMN APFS.SYS_PROG.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN APFS.SYS_PROG.PROG_ORDR IS '프로그램순서';
COMMENT ON COLUMN APFS.SYS_PROG.SYS_SE_CD IS '시스템구분코드';
COMMENT ON COLUMN APFS.SYS_PROG.USE_YN IS '사용여부';
COMMENT ON COLUMN APFS.SYS_PROG.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.SYS_PROG.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.SYS_PROG.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.SYS_PROG.MDFCN_YMD IS '수정일자';

CREATE TABLE APFS.SYS_ROLE (
	ROLE_ID VARCHAR(20) NOT NULL,
	UP_ROLE_ID VARCHAR(20),
	ROLE_NM VARCHAR(40),
	SYS_SE_CD VARCHAR(3),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (ROLE_ID)
);
COMMENT ON TABLE  APFS.SYS_ROLE IS '역할 관리';
COMMENT ON COLUMN APFS.SYS_ROLE.ROLE_ID IS '역할ID';
COMMENT ON COLUMN APFS.SYS_ROLE.UP_ROLE_ID IS '상위역할ID';
COMMENT ON COLUMN APFS.SYS_ROLE.ROLE_NM IS '역할명';
COMMENT ON COLUMN APFS.SYS_ROLE.SYS_SE_CD IS '시스템구분코드';
COMMENT ON COLUMN APFS.SYS_ROLE.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.SYS_ROLE.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.SYS_ROLE.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.SYS_ROLE.MDFCN_YMD IS '수정일자';

CREATE TABLE APFS.SYS_ROLE_MENU (
	ROLE_ID VARCHAR(20) NOT NULL,
	MENU_ID VARCHAR(20) NOT NULL,
	USE_YN CHAR(1),
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (ROLE_ID, MENU_ID)
);
COMMENT ON TABLE  APFS.SYS_ROLE_MENU IS '롤별메뉴관리';
COMMENT ON COLUMN APFS.SYS_ROLE_MENU.ROLE_ID IS '역할ID';
COMMENT ON COLUMN APFS.SYS_ROLE_MENU.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN APFS.SYS_ROLE_MENU.USE_YN IS '사용여부';
COMMENT ON COLUMN APFS.SYS_ROLE_MENU.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.SYS_ROLE_MENU.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.SYS_ROLE_MENU.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.SYS_ROLE_MENU.MDFCN_YMD IS '수정일자';

CREATE TABLE APFS.SYS_ROLE_PROG (
	ROLE_ID VARCHAR(20) NOT NULL,
	PROG_ID VARCHAR(20) NOT NULL,
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (ROLE_ID, PROG_ID)
);
COMMENT ON TABLE  APFS.SYS_ROLE_PROG IS '역할별프로그램관리';
COMMENT ON COLUMN APFS.SYS_ROLE_PROG.ROLE_ID IS '역할ID';
COMMENT ON COLUMN APFS.SYS_ROLE_PROG.PROG_ID IS '프로그램ID';
COMMENT ON COLUMN APFS.SYS_ROLE_PROG.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.SYS_ROLE_PROG.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.SYS_ROLE_PROG.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.SYS_ROLE_PROG.MDFCN_YMD IS '수정일자';

CREATE TABLE APFS.SYS_ROLE_USER (
	ROLE_ID VARCHAR(20) NOT NULL,
	USER_NO VARCHAR(20) NOT NULL,
	RGTR_NO VARCHAR(20),
	REG_YMD DATE,
	MDFR_NO VARCHAR(20),
	MDFCN_YMD DATE,
	PRIMARY KEY (ROLE_ID, USER_NO)
);
COMMENT ON TABLE  APFS.SYS_ROLE_USER IS '역할별사용자관리';
COMMENT ON COLUMN APFS.SYS_ROLE_USER.ROLE_ID IS '역할ID';
COMMENT ON COLUMN APFS.SYS_ROLE_USER.USER_NO IS '사용자번호';
COMMENT ON COLUMN APFS.SYS_ROLE_USER.RGTR_NO IS '등록자번호';
COMMENT ON COLUMN APFS.SYS_ROLE_USER.REG_YMD IS '등록일자';
COMMENT ON COLUMN APFS.SYS_ROLE_USER.MDFR_NO IS '수정자번호';
COMMENT ON COLUMN APFS.SYS_ROLE_USER.MDFCN_YMD IS '수정일자';

CREATE TABLE APFS.SYS_CNTN_HST (
	SN INTEGER NOT NULL,
	PROG_URL VARCHAR(500),
	USER_NO VARCHAR(20),
	CNTN_SE_CD VARCHAR(10),
	CNTN_DT DATE,
	CNTN_YR CHAR(4),
	CNTN_MM CHAR(2),
	CNTN_DD CHAR(2),
	IP_ADDR VARCHAR(80),
	SRVR_NM VARCHAR(100),
	SYS_SE_CD VARCHAR(3),
	PRIMARY KEY (SN)
);
COMMENT ON TABLE  APFS.SYS_CNTN_HST IS '프로그램접속이력';
COMMENT ON COLUMN APFS.SYS_CNTN_HST.SN IS '일련번호';
COMMENT ON COLUMN APFS.SYS_CNTN_HST.PROG_URL IS '프로그램URL';
COMMENT ON COLUMN APFS.SYS_CNTN_HST.USER_NO IS '사용자번호';
COMMENT ON COLUMN APFS.SYS_CNTN_HST.CNTN_SE_CD IS '접속구분코드';
COMMENT ON COLUMN APFS.SYS_CNTN_HST.CNTN_DT IS '접속일시';
COMMENT ON COLUMN APFS.SYS_CNTN_HST.CNTN_YR IS '접속연도';
COMMENT ON COLUMN APFS.SYS_CNTN_HST.CNTN_MM IS '접속월';
COMMENT ON COLUMN APFS.SYS_CNTN_HST.CNTN_DD IS '접속일';
COMMENT ON COLUMN APFS.SYS_CNTN_HST.IP_ADDR IS 'IP주소';
COMMENT ON COLUMN APFS.SYS_CNTN_HST.SRVR_NM IS '서버명';
COMMENT ON COLUMN APFS.SYS_CNTN_HST.SYS_SE_CD IS '시스템구분코드';

CREATE TABLE APFS.SYS_LGN_HST (
	SN INTEGER NOT NULL,
	USER_NO VARCHAR(20),
	USER_ID VARCHAR(100),
	LGN_DT DATE,
	LGN_YR CHAR(4),
	LGN_MM CHAR(2),
	LGN_DD CHAR(2),
	LGN_STUS_CD VARCHAR(2),
	IP_ADDR VARCHAR(80),
	SRVR_NM VARCHAR(100),
	SYS_SE_CD VARCHAR(3),
	PRIMARY KEY (SN)
);
COMMENT ON TABLE  APFS.SYS_LGN_HST IS '로그인이력';
COMMENT ON COLUMN APFS.SYS_LGN_HST.SN IS '일련번호';
COMMENT ON COLUMN APFS.SYS_LGN_HST.USER_NO IS '사용자번호';
COMMENT ON COLUMN APFS.SYS_LGN_HST.USER_ID IS '사용자ID';
COMMENT ON COLUMN APFS.SYS_LGN_HST.LGN_DT IS '로그인일시';
COMMENT ON COLUMN APFS.SYS_LGN_HST.LGN_YR IS '로그인연도';
COMMENT ON COLUMN APFS.SYS_LGN_HST.LGN_MM IS '로그인월';
COMMENT ON COLUMN APFS.SYS_LGN_HST.LGN_DD IS '로그인일';
COMMENT ON COLUMN APFS.SYS_LGN_HST.LGN_STUS_CD IS '로그인상태코드';
COMMENT ON COLUMN APFS.SYS_LGN_HST.IP_ADDR IS 'IP주소';
COMMENT ON COLUMN APFS.SYS_LGN_HST.SRVR_NM IS '서버명';
COMMENT ON COLUMN APFS.SYS_LGN_HST.SYS_SE_CD IS '시스템구분코드';

CREATE TABLE APFS.SYS_DOWN_HST (
	SN NUMERIC(10,0) NOT NULL,
	ATCH_FILE_SN NUMERIC(10,0) NOT NULL,
	PROG_URL VARCHAR(500),
	USER_NO VARCHAR(20),
	DOWN_RESN VARCHAR(200),
	CNTN_DT TIMESTAMP,
	CNTN_MM CHAR(2),
	CNTN_DD CHAR(2),
	IP_ADDR VARCHAR(80),
	SRVR_NM VARCHAR(300),
	SYS_SE_CD VARCHAR(3),
	PRIMARY KEY (SN)
);

COMMENT ON TABLE  APFS.SYS_DOWN_HST    IS '다운로드이력';
COMMENT ON COLUMN APFS.SYS_DOWN_HST.SN    IS '일련번호';
COMMENT ON COLUMN APFS.SYS_DOWN_HST.ATCH_FILE_SN    IS '첨부파일일련번호';
COMMENT ON COLUMN APFS.SYS_DOWN_HST.PROG_URL    IS '프로그램URL';
COMMENT ON COLUMN APFS.SYS_DOWN_HST.USER_NO    IS '사용자번호';
COMMENT ON COLUMN APFS.SYS_DOWN_HST.DOWN_RESN    IS '다운사유';
COMMENT ON COLUMN APFS.SYS_DOWN_HST.CNTN_DT    IS '접속일시';
COMMENT ON COLUMN APFS.SYS_DOWN_HST.CNTN_MM    IS '접속월';
COMMENT ON COLUMN APFS.SYS_DOWN_HST.CNTN_DD    IS '접속일';
COMMENT ON COLUMN APFS.SYS_DOWN_HST.IP_ADDR    IS 'IP주소';
COMMENT ON COLUMN APFS.SYS_DOWN_HST.SRVR_NM    IS '서버명';
COMMENT ON COLUMN APFS.SYS_DOWN_HST.SYS_SE_CD    IS '시스템구분코드';

CREATE TABLE APFS.SYS_INFO_HST (
	SN NUMERIC(10,0) NOT NULL,
	USER_NO VARCHAR(20),
	CNTN_SE_NM VARCHAR(200),
	KEY1 VARCHAR(20),
	KEY2 VARCHAR(20),
	KEY3 VARCHAR(20),
	KEY4 VARCHAR(20),
	CNTN_DT TIMESTAMP,
	IP_ADDR VARCHAR(80),
	SRVR_NM VARCHAR(300),
	SYS_SE_CD VARCHAR(3),
	PRIMARY KEY (SN)
);

COMMENT ON TABLE APFS.SYS_INFO_HST    IS '정보조회이력';
COMMENT ON COLUMN APFS.SYS_INFO_HST.SN    IS '일련번호';
COMMENT ON COLUMN APFS.SYS_INFO_HST.USER_NO    IS '사용자번호';
COMMENT ON COLUMN APFS.SYS_INFO_HST.CNTN_SE_NM    IS '접속구분명';
COMMENT ON COLUMN APFS.SYS_INFO_HST.KEY1    IS 'KEY1';
COMMENT ON COLUMN APFS.SYS_INFO_HST.KEY2    IS 'KEY2';
COMMENT ON COLUMN APFS.SYS_INFO_HST.KEY3    IS 'KEY3';
COMMENT ON COLUMN APFS.SYS_INFO_HST.KEY4    IS 'KEY4';
COMMENT ON COLUMN APFS.SYS_INFO_HST.CNTN_DT    IS '접속일시';
COMMENT ON COLUMN APFS.SYS_INFO_HST.IP_ADDR    IS 'IP주소';
COMMENT ON COLUMN APFS.SYS_INFO_HST.SRVR_NM    IS '서버명';
COMMENT ON COLUMN APFS.SYS_INFO_HST.SYS_SE_CD    IS '시스템구분코드';

    

    
